[workspace]
members = [
  "gen-tileset",
  "editor",
]

[package]
name = "game-testbed"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.2.5"

[dependencies.ecs]
path = "ecs"

[dependencies.graphics]
path = "graphics"
