[package]
name = "game-testbed"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26.1"
wgpu = "0.12.0"

env_logger = "0.9.0"
log = "0.4.16"

pollster = "0.2.5"

bytemuck = { version = "1.9.1", features = [ "derive" ] }