[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26.1"

graphics = { path = "../graphics", version = "*" }

serde = { version = "1.0.136", features = ["derive"] }
typetag = "0.1.8"